### PR TITLE
USLS 212/213 Request

### PR DESCRIPTION
**Pull request by sondermanjj**

### CODE REVIEW

**Review by alliclemens — APPROVED** [review]
- [ ] Final functionality has been reviewed and accepted by half of the team -- not yet, I am the first to review, but tasks had been reviewed by multiple team members
- [x] Functionality of the story has been demonstrated without any problems occurring
- [x] All tasks within the user story are done -- one task was not completed, as it was decided it was not needed
- [x] Automated tests pass showing the code is working as expected
- [x] Story has progressed through all phases (In Review, Reviewed, Done, etc.) and been logged at each point

**Review by dicksontc — DISMISSED** [review]
- [ ] Final functionality has been reviewed and accepted by half of the team
- [ ] Functionality of the story has been demonstrated without any problems occurring -- The code written seems to scan the faculty just fine, but the export function gives only undefined lunch tables to the teachers.
- [ ] All tasks within the user story are done -- one task left incomplete due to its irrelevance.
- [ ] Automated tests pass showing the code is working as expected -- There are no tests for making sure the export button works correctly.
- [ ] Story has progressed through all phases (In Review, Reviewed, Done, etc.) and been logged at each point

**Review by dicksontc — COMMENTED** [review]
- [x] Final functionality has been reviewed and accepted by half of the team -- 2 members have reviewed
- [x] Functionality of the story has been demonstrated without any problems occurring -- The code written scans teacher fine and website export sheet displays information.
- [x] All tasks within the user story are done -- one task left incomplete due to its irrelevance.
- [ ] Automated tests pass showing the code is working as expected -- There are no tests for making sure the export button works correctly.
- [x] Story has progressed through all phases (In Review, Reviewed, Done, etc.) and been logged at each point

**Review by Umbralith — COMMENTED** [review]
- The first time I ran scan, it created a sheet called "ScannedSheetConflicts_468932103" and it didn't show the schedule changes in the add-on menu. I couldn't recreate the problem afterwards. 
- Website Export looks good 
- Teacher statistics look good
- Testing for statistics breaks when ran
- Didn't see testing for the export button, but I'm not sure if we have the capability for that, so that's all good

**Review by Umbralith — APPROVED** [review]

**Pull request merged**
